/**
 * PRISM NBAPI
 * This is a PRISM NBAPI API Client module.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AclEntryFlow'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AclEntryFlow'));
  } else {
    // Browser globals (root is window)
    if (!root.PrismNbapi) {
      root.PrismNbapi = {};
    }
    root.PrismNbapi.AclEntry = factory(root.PrismNbapi.ApiClient, root.PrismNbapi.AclEntryFlow);
  }
}(this, function(ApiClient, AclEntryFlow) {
  'use strict';




  /**
   * The AclEntry model module.
   * @module model/AclEntry
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>AclEntry</code>.
   * @alias module:model/AclEntry
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>AclEntry</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AclEntry} obj Optional instance to populate.
   * @return {module:model/AclEntry} The populated <code>AclEntry</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('match_order')) {
        obj['match_order'] = ApiClient.convertToType(data['match_order'], 'String');
      }
      if (data.hasOwnProperty('src_host')) {
        obj['src_host'] = ApiClient.convertToType(data['src_host'], 'String');
      }
      if (data.hasOwnProperty('protocol')) {
        obj['protocol'] = ApiClient.convertToType(data['protocol'], 'String');
      }
      if (data.hasOwnProperty('dst_host')) {
        obj['dst_host'] = ApiClient.convertToType(data['dst_host'], 'String');
      }
      if (data.hasOwnProperty('src_wildcard')) {
        obj['src_wildcard'] = ApiClient.convertToType(data['src_wildcard'], 'String');
      }
      if (data.hasOwnProperty('flow')) {
        obj['flow'] = ApiClient.convertToType(data['flow'], [AclEntryFlow]);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/AclEntry.MatchOrderEnum} match_order
   */
  exports.prototype['match_order'] = undefined;
  /**
   * @member {String} src_host
   */
  exports.prototype['src_host'] = undefined;
  /**
   * @member {module:model/AclEntry.ProtocolEnum} protocol
   */
  exports.prototype['protocol'] = undefined;
  /**
   * @member {String} dst_host
   */
  exports.prototype['dst_host'] = undefined;
  /**
   * @member {String} src_wildcard
   */
  exports.prototype['src_wildcard'] = undefined;
  /**
   * @member {Array.<module:model/AclEntryFlow>} flow
   */
  exports.prototype['flow'] = undefined;


  /**
   * Allowed values for the <code>match_order</code> property.
   * @enum {String}
   * @readonly
   */
  exports.MatchOrderEnum = {
    /**
     * value: "deny"
     * @const
     */
    "deny": "deny",
    /**
     * value: "permit"
     * @const
     */
    "permit": "permit"  };

  /**
   * Allowed values for the <code>protocol</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ProtocolEnum = {
    /**
     * value: "tcp"
     * @const
     */
    "tcp": "tcp",
    /**
     * value: "udp"
     * @const
     */
    "udp": "udp"  };


  return exports;
}));


