/**
 * PRISM NBAPI
 * This is a PRISM NBAPI API Client module.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AclInfoDataData'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AclInfoDataData'));
  } else {
    // Browser globals (root is window)
    if (!root.PrismNbapi) {
      root.PrismNbapi = {};
    }
    root.PrismNbapi.AclInfoData = factory(root.PrismNbapi.ApiClient, root.PrismNbapi.AclInfoDataData);
  }
}(this, function(ApiClient, AclInfoDataData) {
  'use strict';




  /**
   * The AclInfoData model module.
   * @module model/AclInfoData
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>AclInfoData</code>.
   * @alias module:model/AclInfoData
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>AclInfoData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AclInfoData} obj Optional instance to populate.
   * @return {module:model/AclInfoData} The populated <code>AclInfoData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], [AclInfoDataData]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/AclInfoDataData>} data
   */
  exports.prototype['data'] = undefined;



  return exports;
}));


