/**
 * PRISM NBAPI
 * This is a PRISM NBAPI API Client module.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AclEntry'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AclEntry'));
  } else {
    // Browser globals (root is window)
    if (!root.PrismNbapi) {
      root.PrismNbapi = {};
    }
    root.PrismNbapi.AclInfoDataData = factory(root.PrismNbapi.ApiClient, root.PrismNbapi.AclEntry);
  }
}(this, function(ApiClient, AclEntry) {
  'use strict';




  /**
   * The AclInfoDataData model module.
   * @module model/AclInfoDataData
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>AclInfoDataData</code>.
   * @alias module:model/AclInfoDataData
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>AclInfoDataData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AclInfoDataData} obj Optional instance to populate.
   * @return {module:model/AclInfoDataData} The populated <code>AclInfoDataData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('acl_entry')) {
        obj['acl_entry'] = ApiClient.convertToType(data['acl_entry'], [AclEntry]);
      }
      if (data.hasOwnProperty('acl_number')) {
        obj['acl_number'] = ApiClient.convertToType(data['acl_number'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/AclEntry>} acl_entry
   */
  exports.prototype['acl_entry'] = undefined;
  /**
   * @member {String} acl_number
   */
  exports.prototype['acl_number'] = undefined;



  return exports;
}));


