/**
 * PRISM NBAPI
 * This is a PRISM NBAPI API Client module.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SettingInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SettingInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.PrismNbapi) {
      root.PrismNbapi = {};
    }
    root.PrismNbapi.ConfRoutingProtocolInfo = factory(root.PrismNbapi.ApiClient, root.PrismNbapi.SettingInfo);
  }
}(this, function(ApiClient, SettingInfo) {
  'use strict';




  /**
   * The ConfRoutingProtocolInfo model module.
   * @module model/ConfRoutingProtocolInfo
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ConfRoutingProtocolInfo</code>.
   * @alias module:model/ConfRoutingProtocolInfo
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>ConfRoutingProtocolInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ConfRoutingProtocolInfo} obj Optional instance to populate.
   * @return {module:model/ConfRoutingProtocolInfo} The populated <code>ConfRoutingProtocolInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('protocol')) {
        obj['protocol'] = ApiClient.convertToType(data['protocol'], 'String');
      }
      if (data.hasOwnProperty('update')) {
        obj['update'] = SettingInfo.constructFromObject(data['update']);
      }
      if (data.hasOwnProperty('delete')) {
        obj['delete'] = SettingInfo.constructFromObject(data['delete']);
      }
      if (data.hasOwnProperty('as_id')) {
        obj['as_id'] = ApiClient.convertToType(data['as_id'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/ConfRoutingProtocolInfo.ProtocolEnum} protocol
   */
  exports.prototype['protocol'] = undefined;
  /**
   * @member {module:model/SettingInfo} update
   */
  exports.prototype['update'] = undefined;
  /**
   * @member {module:model/SettingInfo} delete
   */
  exports.prototype['delete'] = undefined;
  /**
   * @member {String} as_id
   */
  exports.prototype['as_id'] = undefined;


  /**
   * Allowed values for the <code>protocol</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ProtocolEnum = {
    /**
     * value: "bgp"
     * @const
     */
    "bgp": "bgp",
    /**
     * value: "ospf"
     * @const
     */
    "ospf": "ospf",
    /**
     * value: "static"
     * @const
     */
    "static": "static"  };


  return exports;
}));


