/**
 * PRISM NBAPI
 * This is a PRISM NBAPI API Client module.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PrismNbapi) {
      root.PrismNbapi = {};
    }
    root.PrismNbapi.DhcpSvrInfoHosts = factory(root.PrismNbapi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DhcpSvrInfoHosts model module.
   * @module model/DhcpSvrInfoHosts
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>DhcpSvrInfoHosts</code>.
   * @alias module:model/DhcpSvrInfoHosts
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>DhcpSvrInfoHosts</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DhcpSvrInfoHosts} obj Optional instance to populate.
   * @return {module:model/DhcpSvrInfoHosts} The populated <code>DhcpSvrInfoHosts</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('mac_address')) {
        obj['mac_address'] = ApiClient.convertToType(data['mac_address'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('ip_address')) {
        obj['ip_address'] = ApiClient.convertToType(data['ip_address'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} mac_address
   */
  exports.prototype['mac_address'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} ip_address
   */
  exports.prototype['ip_address'] = undefined;



  return exports;
}));


