/**
 * PRISM NBAPI
 * This is a PRISM NBAPI API Client module.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PrismNbapi) {
      root.PrismNbapi = {};
    }
    root.PrismNbapi.InterfaceInfo = factory(root.PrismNbapi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The InterfaceInfo model module.
   * @module model/InterfaceInfo
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>InterfaceInfo</code>.
   * @alias module:model/InterfaceInfo
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>InterfaceInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InterfaceInfo} obj Optional instance to populate.
   * @return {module:model/InterfaceInfo} The populated <code>InterfaceInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('port')) {
        obj['port'] = ApiClient.convertToType(data['port'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('dpid')) {
        obj['dpid'] = ApiClient.convertToType(data['dpid'], 'String');
      }
      if (data.hasOwnProperty('default_vrf')) {
        obj['default_vrf'] = ApiClient.convertToType(data['default_vrf'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} port
   */
  exports.prototype['port'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} dpid
   */
  exports.prototype['dpid'] = undefined;
  /**
   * @member {String} default_vrf
   */
  exports.prototype['default_vrf'] = undefined;



  return exports;
}));


