/**
 * PRISM NBAPI
 * This is a PRISM NBAPI API Client module.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PrismNbapi) {
      root.PrismNbapi = {};
    }
    root.PrismNbapi.IntfStats = factory(root.PrismNbapi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The IntfStats model module.
   * @module model/IntfStats
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>IntfStats</code>.
   * @alias module:model/IntfStats
   * @class
   */
  var exports = function() {
    var _this = this;
























  };

  /**
   * Constructs a <code>IntfStats</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/IntfStats} obj Optional instance to populate.
   * @return {module:model/IntfStats} The populated <code>IntfStats</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('collisions')) {
        obj['collisions'] = ApiClient.convertToType(data['collisions'], 'Number');
      }
      if (data.hasOwnProperty('multicast')) {
        obj['multicast'] = ApiClient.convertToType(data['multicast'], 'Number');
      }
      if (data.hasOwnProperty('rx_bytes')) {
        obj['rx_bytes'] = ApiClient.convertToType(data['rx_bytes'], 'Number');
      }
      if (data.hasOwnProperty('rx_compressed')) {
        obj['rx_compressed'] = ApiClient.convertToType(data['rx_compressed'], 'Number');
      }
      if (data.hasOwnProperty('rx_crc_errors')) {
        obj['rx_crc_errors'] = ApiClient.convertToType(data['rx_crc_errors'], 'Number');
      }
      if (data.hasOwnProperty('rx_dropped')) {
        obj['rx_dropped'] = ApiClient.convertToType(data['rx_dropped'], 'Number');
      }
      if (data.hasOwnProperty('rx_errors')) {
        obj['rx_errors'] = ApiClient.convertToType(data['rx_errors'], 'Number');
      }
      if (data.hasOwnProperty('rx_fifo_errors')) {
        obj['rx_fifo_errors'] = ApiClient.convertToType(data['rx_fifo_errors'], 'Number');
      }
      if (data.hasOwnProperty('rx_frame_errors')) {
        obj['rx_frame_errors'] = ApiClient.convertToType(data['rx_frame_errors'], 'Number');
      }
      if (data.hasOwnProperty('rx_length_errors')) {
        obj['rx_length_errors'] = ApiClient.convertToType(data['rx_length_errors'], 'Number');
      }
      if (data.hasOwnProperty('rx_missed_errors')) {
        obj['rx_missed_errors'] = ApiClient.convertToType(data['rx_missed_errors'], 'Number');
      }
      if (data.hasOwnProperty('rx_over_errors')) {
        obj['rx_over_errors'] = ApiClient.convertToType(data['rx_over_errors'], 'Number');
      }
      if (data.hasOwnProperty('rx_packets')) {
        obj['rx_packets'] = ApiClient.convertToType(data['rx_packets'], 'Number');
      }
      if (data.hasOwnProperty('tx_aborted_errors')) {
        obj['tx_aborted_errors'] = ApiClient.convertToType(data['tx_aborted_errors'], 'Number');
      }
      if (data.hasOwnProperty('tx_bytes')) {
        obj['tx_bytes'] = ApiClient.convertToType(data['tx_bytes'], 'Number');
      }
      if (data.hasOwnProperty('tx_carrier_errors')) {
        obj['tx_carrier_errors'] = ApiClient.convertToType(data['tx_carrier_errors'], 'String');
      }
      if (data.hasOwnProperty('tx_compressed')) {
        obj['tx_compressed'] = ApiClient.convertToType(data['tx_compressed'], 'Number');
      }
      if (data.hasOwnProperty('tx_dropped')) {
        obj['tx_dropped'] = ApiClient.convertToType(data['tx_dropped'], 'Number');
      }
      if (data.hasOwnProperty('tx_errors')) {
        obj['tx_errors'] = ApiClient.convertToType(data['tx_errors'], 'Number');
      }
      if (data.hasOwnProperty('tx_fifo_errors')) {
        obj['tx_fifo_errors'] = ApiClient.convertToType(data['tx_fifo_errors'], 'Number');
      }
      if (data.hasOwnProperty('tx_heartbeat_errors')) {
        obj['tx_heartbeat_errors'] = ApiClient.convertToType(data['tx_heartbeat_errors'], 'Number');
      }
      if (data.hasOwnProperty('tx_packets')) {
        obj['tx_packets'] = ApiClient.convertToType(data['tx_packets'], 'Number');
      }
      if (data.hasOwnProperty('tx_window_errors')) {
        obj['tx_window_errors'] = ApiClient.convertToType(data['tx_window_errors'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} collisions
   */
  exports.prototype['collisions'] = undefined;
  /**
   * @member {Number} multicast
   */
  exports.prototype['multicast'] = undefined;
  /**
   * @member {Number} rx_bytes
   */
  exports.prototype['rx_bytes'] = undefined;
  /**
   * @member {Number} rx_compressed
   */
  exports.prototype['rx_compressed'] = undefined;
  /**
   * @member {Number} rx_crc_errors
   */
  exports.prototype['rx_crc_errors'] = undefined;
  /**
   * @member {Number} rx_dropped
   */
  exports.prototype['rx_dropped'] = undefined;
  /**
   * @member {Number} rx_errors
   */
  exports.prototype['rx_errors'] = undefined;
  /**
   * @member {Number} rx_fifo_errors
   */
  exports.prototype['rx_fifo_errors'] = undefined;
  /**
   * @member {Number} rx_frame_errors
   */
  exports.prototype['rx_frame_errors'] = undefined;
  /**
   * @member {Number} rx_length_errors
   */
  exports.prototype['rx_length_errors'] = undefined;
  /**
   * @member {Number} rx_missed_errors
   */
  exports.prototype['rx_missed_errors'] = undefined;
  /**
   * @member {Number} rx_over_errors
   */
  exports.prototype['rx_over_errors'] = undefined;
  /**
   * @member {Number} rx_packets
   */
  exports.prototype['rx_packets'] = undefined;
  /**
   * @member {Number} tx_aborted_errors
   */
  exports.prototype['tx_aborted_errors'] = undefined;
  /**
   * @member {Number} tx_bytes
   */
  exports.prototype['tx_bytes'] = undefined;
  /**
   * @member {String} tx_carrier_errors
   */
  exports.prototype['tx_carrier_errors'] = undefined;
  /**
   * @member {Number} tx_compressed
   */
  exports.prototype['tx_compressed'] = undefined;
  /**
   * @member {Number} tx_dropped
   */
  exports.prototype['tx_dropped'] = undefined;
  /**
   * @member {Number} tx_errors
   */
  exports.prototype['tx_errors'] = undefined;
  /**
   * @member {Number} tx_fifo_errors
   */
  exports.prototype['tx_fifo_errors'] = undefined;
  /**
   * @member {Number} tx_heartbeat_errors
   */
  exports.prototype['tx_heartbeat_errors'] = undefined;
  /**
   * @member {Number} tx_packets
   */
  exports.prototype['tx_packets'] = undefined;
  /**
   * @member {Number} tx_window_errors
   */
  exports.prototype['tx_window_errors'] = undefined;



  return exports;
}));


