/**
 * PRISM NBAPI
 * This is a PRISM NBAPI API Client module.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PrismNbapi) {
      root.PrismNbapi = {};
    }
    root.PrismNbapi.MulticastInfoPhyint = factory(root.PrismNbapi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The MulticastInfoPhyint model module.
   * @module model/MulticastInfoPhyint
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>MulticastInfoPhyint</code>.
   * @alias module:model/MulticastInfoPhyint
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>MulticastInfoPhyint</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MulticastInfoPhyint} obj Optional instance to populate.
   * @return {module:model/MulticastInfoPhyint} The populated <code>MulticastInfoPhyint</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ifname')) {
        obj['ifname'] = ApiClient.convertToType(data['ifname'], 'String');
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = ApiClient.convertToType(data['state'], 'String');
      }
      if (data.hasOwnProperty('dr_priority')) {
        obj['dr_priority'] = ApiClient.convertToType(data['dr_priority'], 'String');
      }
      if (data.hasOwnProperty('ttl_threshold')) {
        obj['ttl_threshold'] = ApiClient.convertToType(data['ttl_threshold'], 'String');
      }
      if (data.hasOwnProperty('distance')) {
        obj['distance'] = ApiClient.convertToType(data['distance'], 'String');
      }
      if (data.hasOwnProperty('metric')) {
        obj['metric'] = ApiClient.convertToType(data['metric'], 'String');
      }
      if (data.hasOwnProperty('altnet')) {
        obj['altnet'] = ApiClient.convertToType(data['altnet'], 'String');
      }
      if (data.hasOwnProperty('scope')) {
        obj['scope'] = ApiClient.convertToType(data['scope'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} ifname
   */
  exports.prototype['ifname'] = undefined;
  /**
   * @member {module:model/MulticastInfoPhyint.StateEnum} state
   */
  exports.prototype['state'] = undefined;
  /**
   * @member {String} dr_priority
   */
  exports.prototype['dr_priority'] = undefined;
  /**
   * @member {String} ttl_threshold
   */
  exports.prototype['ttl_threshold'] = undefined;
  /**
   * @member {String} distance
   */
  exports.prototype['distance'] = undefined;
  /**
   * @member {String} metric
   */
  exports.prototype['metric'] = undefined;
  /**
   * @member {String} altnet
   */
  exports.prototype['altnet'] = undefined;
  /**
   * @member {String} scope
   */
  exports.prototype['scope'] = undefined;


  /**
   * Allowed values for the <code>state</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StateEnum = {
    /**
     * value: "ENABLE"
     * @const
     */
    "ENABLE": "ENABLE",
    /**
     * value: "DISABLE"
     * @const
     */
    "DISABLE": "DISABLE"  };


  return exports;
}));


