/**
 * PRISM NBAPI
 * This is a PRISM NBAPI API Client module.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PrismNbapi) {
      root.PrismNbapi = {};
    }
    root.PrismNbapi.MulticastInfoSptThreshold = factory(root.PrismNbapi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The MulticastInfoSptThreshold model module.
   * @module model/MulticastInfoSptThreshold
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>MulticastInfoSptThreshold</code>.
   * @alias module:model/MulticastInfoSptThreshold
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>MulticastInfoSptThreshold</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MulticastInfoSptThreshold} obj Optional instance to populate.
   * @return {module:model/MulticastInfoSptThreshold} The populated <code>MulticastInfoSptThreshold</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('rate')) {
        obj['rate'] = ApiClient.convertToType(data['rate'], 'String');
      }
      if (data.hasOwnProperty('packets')) {
        obj['packets'] = ApiClient.convertToType(data['packets'], 'String');
      }
      if (data.hasOwnProperty('interval')) {
        obj['interval'] = ApiClient.convertToType(data['interval'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} rate
   */
  exports.prototype['rate'] = undefined;
  /**
   * @member {String} packets
   */
  exports.prototype['packets'] = undefined;
  /**
   * @member {String} interval
   */
  exports.prototype['interval'] = undefined;



  return exports;
}));


