/**
 * PRISM NBAPI
 * This is a PRISM NBAPI API Client module.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PrismNbapi) {
      root.PrismNbapi = {};
    }
    root.PrismNbapi.MulticastInfoBsrCandi = factory(root.PrismNbapi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The MulticastInfoBsrCandi model module.
   * @module model/MulticastInfoBsrCandi
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>MulticastInfoBsrCandi</code>.
   * @alias module:model/MulticastInfoBsrCandi
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>MulticastInfoBsrCandi</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MulticastInfoBsrCandi} obj Optional instance to populate.
   * @return {module:model/MulticastInfoBsrCandi} The populated <code>MulticastInfoBsrCandi</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ifname')) {
        obj['ifname'] = ApiClient.convertToType(data['ifname'], 'String');
      }
      if (data.hasOwnProperty('priority')) {
        obj['priority'] = ApiClient.convertToType(data['priority'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} ifname
   */
  exports.prototype['ifname'] = undefined;
  /**
   * @member {String} priority
   */
  exports.prototype['priority'] = undefined;



  return exports;
}));


