/**
 * PRISM NBAPI
 * This is a PRISM NBAPI API Client module.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MulticastInfoBsrCandi', 'model/MulticastInfoPhyint', 'model/MulticastInfoRpAddr', 'model/MulticastInfoRpCandi', 'model/MulticastInfoSptThreshold'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MulticastInfoBsrCandi'), require('./MulticastInfoPhyint'), require('./MulticastInfoRpAddr'), require('./MulticastInfoRpCandi'), require('./MulticastInfoSptThreshold'));
  } else {
    // Browser globals (root is window)
    if (!root.PrismNbapi) {
      root.PrismNbapi = {};
    }
    root.PrismNbapi.MulticastInfo = factory(root.PrismNbapi.ApiClient, root.PrismNbapi.MulticastInfoBsrCandi, root.PrismNbapi.MulticastInfoPhyint, root.PrismNbapi.MulticastInfoRpAddr, root.PrismNbapi.MulticastInfoRpCandi, root.PrismNbapi.MulticastInfoSptThreshold);
  }
}(this, function(ApiClient, MulticastInfoBsrCandi, MulticastInfoPhyint, MulticastInfoRpAddr, MulticastInfoRpCandi, MulticastInfoSptThreshold) {
  'use strict';




  /**
   * The MulticastInfo model module.
   * @module model/MulticastInfo
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>MulticastInfo</code>.
   * @alias module:model/MulticastInfo
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>MulticastInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MulticastInfo} obj Optional instance to populate.
   * @return {module:model/MulticastInfo} The populated <code>MulticastInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('df_route_dist')) {
        obj['df_route_dist'] = ApiClient.convertToType(data['df_route_dist'], 'String');
      }
      if (data.hasOwnProperty('df_route_met')) {
        obj['df_route_met'] = ApiClient.convertToType(data['df_route_met'], 'String');
      }
      if (data.hasOwnProperty('phyint')) {
        obj['phyint'] = MulticastInfoPhyint.constructFromObject(data['phyint']);
      }
      if (data.hasOwnProperty('rp_addr')) {
        obj['rp_addr'] = MulticastInfoRpAddr.constructFromObject(data['rp_addr']);
      }
      if (data.hasOwnProperty('rp_candi')) {
        obj['rp_candi'] = MulticastInfoRpCandi.constructFromObject(data['rp_candi']);
      }
      if (data.hasOwnProperty('bsr_candi')) {
        obj['bsr_candi'] = MulticastInfoBsrCandi.constructFromObject(data['bsr_candi']);
      }
      if (data.hasOwnProperty('spt_threshold')) {
        obj['spt_threshold'] = MulticastInfoSptThreshold.constructFromObject(data['spt_threshold']);
      }
    }
    return obj;
  }

  /**
   * @member {String} df_route_dist
   */
  exports.prototype['df_route_dist'] = undefined;
  /**
   * @member {String} df_route_met
   */
  exports.prototype['df_route_met'] = undefined;
  /**
   * @member {module:model/MulticastInfoPhyint} phyint
   */
  exports.prototype['phyint'] = undefined;
  /**
   * @member {module:model/MulticastInfoRpAddr} rp_addr
   */
  exports.prototype['rp_addr'] = undefined;
  /**
   * @member {module:model/MulticastInfoRpCandi} rp_candi
   */
  exports.prototype['rp_candi'] = undefined;
  /**
   * @member {module:model/MulticastInfoBsrCandi} bsr_candi
   */
  exports.prototype['bsr_candi'] = undefined;
  /**
   * @member {module:model/MulticastInfoSptThreshold} spt_threshold
   */
  exports.prototype['spt_threshold'] = undefined;



  return exports;
}));


