/**
 * PRISM NBAPI
 * This is a PRISM NBAPI API Client module.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MulticastInfoRpCandiGroupPre'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MulticastInfoRpCandiGroupPre'));
  } else {
    // Browser globals (root is window)
    if (!root.PrismNbapi) {
      root.PrismNbapi = {};
    }
    root.PrismNbapi.MulticastInfoRpCandi = factory(root.PrismNbapi.ApiClient, root.PrismNbapi.MulticastInfoRpCandiGroupPre);
  }
}(this, function(ApiClient, MulticastInfoRpCandiGroupPre) {
  'use strict';




  /**
   * The MulticastInfoRpCandi model module.
   * @module model/MulticastInfoRpCandi
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>MulticastInfoRpCandi</code>.
   * @alias module:model/MulticastInfoRpCandi
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>MulticastInfoRpCandi</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MulticastInfoRpCandi} obj Optional instance to populate.
   * @return {module:model/MulticastInfoRpCandi} The populated <code>MulticastInfoRpCandi</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('priority')) {
        obj['priority'] = ApiClient.convertToType(data['priority'], 'String');
      }
      if (data.hasOwnProperty('time')) {
        obj['time'] = ApiClient.convertToType(data['time'], 'String');
      }
      if (data.hasOwnProperty('group_pre')) {
        obj['group_pre'] = ApiClient.convertToType(data['group_pre'], [MulticastInfoRpCandiGroupPre]);
      }
    }
    return obj;
  }

  /**
   * @member {String} priority
   */
  exports.prototype['priority'] = undefined;
  /**
   * @member {String} time
   */
  exports.prototype['time'] = undefined;
  /**
   * @member {Array.<module:model/MulticastInfoRpCandiGroupPre>} group_pre
   */
  exports.prototype['group_pre'] = undefined;



  return exports;
}));


