/**
 * PRISM NBAPI
 * This is a PRISM NBAPI API Client module.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SettingInfoNeighbor', 'model/SettingInfoNetwork', 'model/SettingInfoRedistribute'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SettingInfoNeighbor'), require('./SettingInfoNetwork'), require('./SettingInfoRedistribute'));
  } else {
    // Browser globals (root is window)
    if (!root.PrismNbapi) {
      root.PrismNbapi = {};
    }
    root.PrismNbapi.RoutingProtocolInfoBgp = factory(root.PrismNbapi.ApiClient, root.PrismNbapi.SettingInfoNeighbor, root.PrismNbapi.SettingInfoNetwork, root.PrismNbapi.SettingInfoRedistribute);
  }
}(this, function(ApiClient, SettingInfoNeighbor, SettingInfoNetwork, SettingInfoRedistribute) {
  'use strict';




  /**
   * The RoutingProtocolInfoBgp model module.
   * @module model/RoutingProtocolInfoBgp
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RoutingProtocolInfoBgp</code>.
   * @alias module:model/RoutingProtocolInfoBgp
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>RoutingProtocolInfoBgp</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RoutingProtocolInfoBgp} obj Optional instance to populate.
   * @return {module:model/RoutingProtocolInfoBgp} The populated <code>RoutingProtocolInfoBgp</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('router_id')) {
        obj['router_id'] = ApiClient.convertToType(data['router_id'], 'String');
      }
      if (data.hasOwnProperty('redistribute')) {
        obj['redistribute'] = ApiClient.convertToType(data['redistribute'], [SettingInfoRedistribute]);
      }
      if (data.hasOwnProperty('network')) {
        obj['network'] = ApiClient.convertToType(data['network'], [SettingInfoNetwork]);
      }
      if (data.hasOwnProperty('neighbor')) {
        obj['neighbor'] = ApiClient.convertToType(data['neighbor'], [SettingInfoNeighbor]);
      }
      if (data.hasOwnProperty('as_id')) {
        obj['as_id'] = ApiClient.convertToType(data['as_id'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} router_id
   */
  exports.prototype['router_id'] = undefined;
  /**
   * @member {Array.<module:model/SettingInfoRedistribute>} redistribute
   */
  exports.prototype['redistribute'] = undefined;
  /**
   * @member {Array.<module:model/SettingInfoNetwork>} network
   */
  exports.prototype['network'] = undefined;
  /**
   * OSPF 라우터의 neighbor를 설정할 때 사용되는 인자. dict를 인자로 가지는 리스트. 각 dict는 neighbor_id 필드를 필수로 가진다.
   * @member {Array.<module:model/SettingInfoNeighbor>} neighbor
   */
  exports.prototype['neighbor'] = undefined;
  /**
   * @member {String} as_id
   */
  exports.prototype['as_id'] = undefined;



  return exports;
}));


