/**
 * PRISM NBAPI
 * This is a PRISM NBAPI API Client module.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RoutingProtocolInfoBgp', 'model/RoutingProtocolInfoOspf'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RoutingProtocolInfoBgp'), require('./RoutingProtocolInfoOspf'));
  } else {
    // Browser globals (root is window)
    if (!root.PrismNbapi) {
      root.PrismNbapi = {};
    }
    root.PrismNbapi.RoutingProtocolInfo = factory(root.PrismNbapi.ApiClient, root.PrismNbapi.RoutingProtocolInfoBgp, root.PrismNbapi.RoutingProtocolInfoOspf);
  }
}(this, function(ApiClient, RoutingProtocolInfoBgp, RoutingProtocolInfoOspf) {
  'use strict';




  /**
   * The RoutingProtocolInfo model module.
   * @module model/RoutingProtocolInfo
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RoutingProtocolInfo</code>.
   * @alias module:model/RoutingProtocolInfo
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>RoutingProtocolInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RoutingProtocolInfo} obj Optional instance to populate.
   * @return {module:model/RoutingProtocolInfo} The populated <code>RoutingProtocolInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('bgp')) {
        obj['bgp'] = RoutingProtocolInfoBgp.constructFromObject(data['bgp']);
      }
      if (data.hasOwnProperty('tenant_name')) {
        obj['tenant_name'] = ApiClient.convertToType(data['tenant_name'], 'String');
      }
      if (data.hasOwnProperty('ospf')) {
        obj['ospf'] = RoutingProtocolInfoOspf.constructFromObject(data['ospf']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/RoutingProtocolInfoBgp} bgp
   */
  exports.prototype['bgp'] = undefined;
  /**
   * @member {String} tenant_name
   */
  exports.prototype['tenant_name'] = undefined;
  /**
   * @member {module:model/RoutingProtocolInfoOspf} ospf
   */
  exports.prototype['ospf'] = undefined;



  return exports;
}));


