/**
 * PRISM NBAPI
 * This is a PRISM NBAPI API Client module.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PrismNbapi) {
      root.PrismNbapi = {};
    }
    root.PrismNbapi.RoutingProtocolInfoOspfArea = factory(root.PrismNbapi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RoutingProtocolInfoOspfArea model module.
   * @module model/RoutingProtocolInfoOspfArea
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RoutingProtocolInfoOspfArea</code>.
   * @alias module:model/RoutingProtocolInfoOspfArea
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>RoutingProtocolInfoOspfArea</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RoutingProtocolInfoOspfArea} obj Optional instance to populate.
   * @return {module:model/RoutingProtocolInfoOspfArea} The populated <code>RoutingProtocolInfoOspfArea</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('range')) {
        obj['range'] = ApiClient.convertToType(data['range'], 'String');
      }
      if (data.hasOwnProperty('area')) {
        obj['area'] = ApiClient.convertToType(data['area'], 'String');
      }
    }
    return obj;
  }

  /**
   * 해당 area가 관리하는 네트워크 대역. 127.0.0.1/24 식으로 입력
   * @member {String} range
   */
  exports.prototype['range'] = undefined;
  /**
   * OSPF area 주소
   * @member {String} area
   */
  exports.prototype['area'] = undefined;



  return exports;
}));


