/**
 * PRISM NBAPI
 * This is a PRISM NBAPI API Client module.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/RoutingProtocolInfoOspfArea', 'model/RoutingProtocolInfoOspfNeighbor', 'model/SettingInfoNetwork', 'model/SettingInfoRedistribute'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./RoutingProtocolInfoOspfArea'), require('./RoutingProtocolInfoOspfNeighbor'), require('./SettingInfoNetwork'), require('./SettingInfoRedistribute'));
  } else {
    // Browser globals (root is window)
    if (!root.PrismNbapi) {
      root.PrismNbapi = {};
    }
    root.PrismNbapi.RoutingProtocolInfoOspf = factory(root.PrismNbapi.ApiClient, root.PrismNbapi.RoutingProtocolInfoOspfArea, root.PrismNbapi.RoutingProtocolInfoOspfNeighbor, root.PrismNbapi.SettingInfoNetwork, root.PrismNbapi.SettingInfoRedistribute);
  }
}(this, function(ApiClient, RoutingProtocolInfoOspfArea, RoutingProtocolInfoOspfNeighbor, SettingInfoNetwork, SettingInfoRedistribute) {
  'use strict';




  /**
   * The RoutingProtocolInfoOspf model module.
   * @module model/RoutingProtocolInfoOspf
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RoutingProtocolInfoOspf</code>.
   * @alias module:model/RoutingProtocolInfoOspf
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>RoutingProtocolInfoOspf</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RoutingProtocolInfoOspf} obj Optional instance to populate.
   * @return {module:model/RoutingProtocolInfoOspf} The populated <code>RoutingProtocolInfoOspf</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('router_id')) {
        obj['router_id'] = ApiClient.convertToType(data['router_id'], 'String');
      }
      if (data.hasOwnProperty('redistribute')) {
        obj['redistribute'] = ApiClient.convertToType(data['redistribute'], [SettingInfoRedistribute]);
      }
      if (data.hasOwnProperty('network')) {
        obj['network'] = ApiClient.convertToType(data['network'], [SettingInfoNetwork]);
      }
      if (data.hasOwnProperty('neighbor')) {
        obj['neighbor'] = ApiClient.convertToType(data['neighbor'], [RoutingProtocolInfoOspfNeighbor]);
      }
      if (data.hasOwnProperty('area')) {
        obj['area'] = ApiClient.convertToType(data['area'], [RoutingProtocolInfoOspfArea]);
      }
    }
    return obj;
  }

  /**
   * @member {String} router_id
   */
  exports.prototype['router_id'] = undefined;
  /**
   * @member {Array.<module:model/SettingInfoRedistribute>} redistribute
   */
  exports.prototype['redistribute'] = undefined;
  /**
   * @member {Array.<module:model/SettingInfoNetwork>} network
   */
  exports.prototype['network'] = undefined;
  /**
   * @member {Array.<module:model/RoutingProtocolInfoOspfNeighbor>} neighbor
   */
  exports.prototype['neighbor'] = undefined;
  /**
   * @member {Array.<module:model/RoutingProtocolInfoOspfArea>} area
   */
  exports.prototype['area'] = undefined;



  return exports;
}));


