/**
 * PRISM NBAPI
 * This is a PRISM NBAPI API Client module.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PrismNbapi) {
      root.PrismNbapi = {};
    }
    root.PrismNbapi.SettingInfoMatch = factory(root.PrismNbapi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SettingInfoMatch model module.
   * @module model/SettingInfoMatch
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SettingInfoMatch</code>.
   * @alias module:model/SettingInfoMatch
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>SettingInfoMatch</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SettingInfoMatch} obj Optional instance to populate.
   * @return {module:model/SettingInfoMatch} The populated <code>SettingInfoMatch</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ipv4_perfix_list')) {
        obj['ipv4_perfix_list'] = ApiClient.convertToType(data['ipv4_perfix_list'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<String>} ipv4_perfix_list
   */
  exports.prototype['ipv4_perfix_list'] = undefined;



  return exports;
}));


