/**
 * PRISM NBAPI
 * This is a PRISM NBAPI API Client module.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SettingInfoArea', 'model/SettingInfoIpv4Prefix', 'model/SettingInfoNeighbor', 'model/SettingInfoNetwork', 'model/SettingInfoRedistribute', 'model/SettingInfoRouteMap'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SettingInfoArea'), require('./SettingInfoIpv4Prefix'), require('./SettingInfoNeighbor'), require('./SettingInfoNetwork'), require('./SettingInfoRedistribute'), require('./SettingInfoRouteMap'));
  } else {
    // Browser globals (root is window)
    if (!root.PrismNbapi) {
      root.PrismNbapi = {};
    }
    root.PrismNbapi.SettingInfo = factory(root.PrismNbapi.ApiClient, root.PrismNbapi.SettingInfoArea, root.PrismNbapi.SettingInfoIpv4Prefix, root.PrismNbapi.SettingInfoNeighbor, root.PrismNbapi.SettingInfoNetwork, root.PrismNbapi.SettingInfoRedistribute, root.PrismNbapi.SettingInfoRouteMap);
  }
}(this, function(ApiClient, SettingInfoArea, SettingInfoIpv4Prefix, SettingInfoNeighbor, SettingInfoNetwork, SettingInfoRedistribute, SettingInfoRouteMap) {
  'use strict';




  /**
   * The SettingInfo model module.
   * @module model/SettingInfo
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SettingInfo</code>.
   * @alias module:model/SettingInfo
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>SettingInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SettingInfo} obj Optional instance to populate.
   * @return {module:model/SettingInfo} The populated <code>SettingInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('router_id')) {
        obj['router_id'] = ApiClient.convertToType(data['router_id'], 'String');
      }
      if (data.hasOwnProperty('as_id')) {
        obj['as_id'] = ApiClient.convertToType(data['as_id'], 'String');
      }
      if (data.hasOwnProperty('network')) {
        obj['network'] = ApiClient.convertToType(data['network'], [SettingInfoNetwork]);
      }
      if (data.hasOwnProperty('area')) {
        obj['area'] = ApiClient.convertToType(data['area'], [SettingInfoArea]);
      }
      if (data.hasOwnProperty('neighbor')) {
        obj['neighbor'] = ApiClient.convertToType(data['neighbor'], [SettingInfoNeighbor]);
      }
      if (data.hasOwnProperty('redistribute')) {
        obj['redistribute'] = ApiClient.convertToType(data['redistribute'], [SettingInfoRedistribute]);
      }
      if (data.hasOwnProperty('ipv4_prefix')) {
        obj['ipv4_prefix'] = ApiClient.convertToType(data['ipv4_prefix'], [SettingInfoIpv4Prefix]);
      }
      if (data.hasOwnProperty('route_map')) {
        obj['route_map'] = ApiClient.convertToType(data['route_map'], [SettingInfoRouteMap]);
      }
    }
    return obj;
  }

  /**
   * @member {String} router_id
   */
  exports.prototype['router_id'] = undefined;
  /**
   * @member {String} as_id
   */
  exports.prototype['as_id'] = undefined;
  /**
   * @member {Array.<module:model/SettingInfoNetwork>} network
   */
  exports.prototype['network'] = undefined;
  /**
   * OSPF area를 설정할 때 사용되는  필드로 dict를 인자로 가지는 리스트. 각 dict는 id와 range 필드를 필수로 가진다.
   * @member {Array.<module:model/SettingInfoArea>} area
   */
  exports.prototype['area'] = undefined;
  /**
   * OSPF 라우터의 neighbor를 설정할 때 사용되는 인자. dict를 인자로 가지는 리스트. 각 dict는 neighbor_id 필드를 필수로 가진다.
   * @member {Array.<module:model/SettingInfoNeighbor>} neighbor
   */
  exports.prototype['neighbor'] = undefined;
  /**
   * OSPF Redistribute 설정
   * @member {Array.<module:model/SettingInfoRedistribute>} redistribute
   */
  exports.prototype['redistribute'] = undefined;
  /**
   * IP prefix-list 설정
   * @member {Array.<module:model/SettingInfoIpv4Prefix>} ipv4_prefix
   */
  exports.prototype['ipv4_prefix'] = undefined;
  /**
   * @member {Array.<module:model/SettingInfoRouteMap>} route_map
   */
  exports.prototype['route_map'] = undefined;



  return exports;
}));


