/**
 * PRISM NBAPI
 * This is a PRISM NBAPI API Client module.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PrismNbapi) {
      root.PrismNbapi = {};
    }
    root.PrismNbapi.SettingInfoNeighbor = factory(root.PrismNbapi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SettingInfoNeighbor model module.
   * @module model/SettingInfoNeighbor
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SettingInfoNeighbor</code>.
   * @alias module:model/SettingInfoNeighbor
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>SettingInfoNeighbor</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SettingInfoNeighbor} obj Optional instance to populate.
   * @return {module:model/SettingInfoNeighbor} The populated <code>SettingInfoNeighbor</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('neighbor_ip')) {
        obj['neighbor_ip'] = ApiClient.convertToType(data['neighbor_ip'], 'String');
      }
      if (data.hasOwnProperty('remote_as')) {
        obj['remote_as'] = ApiClient.convertToType(data['remote_as'], 'Number');
      }
    }
    return obj;
  }

  /**
   * neighbor의 IP address
   * @member {String} neighbor_ip
   */
  exports.prototype['neighbor_ip'] = undefined;
  /**
   * @member {Number} remote_as
   */
  exports.prototype['remote_as'] = undefined;



  return exports;
}));


