/**
 * PRISM NBAPI
 * This is a PRISM NBAPI API Client module.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PrismNbapi) {
      root.PrismNbapi = {};
    }
    root.PrismNbapi.SettingInfoRedistribute = factory(root.PrismNbapi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SettingInfoRedistribute model module.
   * @module model/SettingInfoRedistribute
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SettingInfoRedistribute</code>.
   * @alias module:model/SettingInfoRedistribute
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>SettingInfoRedistribute</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SettingInfoRedistribute} obj Optional instance to populate.
   * @return {module:model/SettingInfoRedistribute} The populated <code>SettingInfoRedistribute</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ip_version')) {
        obj['ip_version'] = ApiClient.convertToType(data['ip_version'], 'String');
      }
      if (data.hasOwnProperty('mode')) {
        obj['mode'] = ApiClient.convertToType(data['mode'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/SettingInfoRedistribute.IpVersionEnum} ip_version
   */
  exports.prototype['ip_version'] = undefined;
  /**
   * @member {module:model/SettingInfoRedistribute.ModeEnum} mode
   */
  exports.prototype['mode'] = undefined;


  /**
   * Allowed values for the <code>ip_version</code> property.
   * @enum {String}
   * @readonly
   */
  exports.IpVersionEnum = {
    /**
     * value: "ipv6"
     * @const
     */
    "ipv6": "ipv6",
    /**
     * value: "ipv4"
     * @const
     */
    "ipv4": "ipv4"  };

  /**
   * Allowed values for the <code>mode</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ModeEnum = {
    /**
     * value: "babel"
     * @const
     */
    "babel": "babel",
    /**
     * value: "bgp"
     * @const
     */
    "bgp": "bgp",
    /**
     * value: "connected"
     * @const
     */
    "connected": "connected",
    /**
     * value: "isis"
     * @const
     */
    "isis": "isis",
    /**
     * value: "kernel"
     * @const
     */
    "kernel": "kernel",
    /**
     * value: "rip"
     * @const
     */
    "rip": "rip",
    /**
     * value: "static"
     * @const
     */
    "static": "static"  };


  return exports;
}));


