/**
 * PRISM NBAPI
 * This is a PRISM NBAPI API Client module.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SettingInfoMatch'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SettingInfoMatch'));
  } else {
    // Browser globals (root is window)
    if (!root.PrismNbapi) {
      root.PrismNbapi = {};
    }
    root.PrismNbapi.SettingInfoRouteMap = factory(root.PrismNbapi.ApiClient, root.PrismNbapi.SettingInfoMatch);
  }
}(this, function(ApiClient, SettingInfoMatch) {
  'use strict';




  /**
   * The SettingInfoRouteMap model module.
   * @module model/SettingInfoRouteMap
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SettingInfoRouteMap</code>.
   * @alias module:model/SettingInfoRouteMap
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>SettingInfoRouteMap</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SettingInfoRouteMap} obj Optional instance to populate.
   * @return {module:model/SettingInfoRouteMap} The populated <code>SettingInfoRouteMap</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('seq')) {
        obj['seq'] = ApiClient.convertToType(data['seq'], 'Number');
      }
      if (data.hasOwnProperty('match')) {
        obj['match'] = SettingInfoMatch.constructFromObject(data['match']);
      }
    }
    return obj;
  }

  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {module:model/SettingInfoRouteMap.TypeEnum} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {Number} seq
   */
  exports.prototype['seq'] = undefined;
  /**
   * @member {module:model/SettingInfoMatch} match
   */
  exports.prototype['match'] = undefined;


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "deny"
     * @const
     */
    "deny": "deny",
    /**
     * value: "permit"
     * @const
     */
    "permit": "permit"  };


  return exports;
}));


