/**
 * PRISM NBAPI
 * This is a PRISM NBAPI API Client module.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.PrismNbapi) {
      root.PrismNbapi = {};
    }
    root.PrismNbapi.VrrpInfo = factory(root.PrismNbapi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The VrrpInfo model module.
   * @module model/VrrpInfo
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>VrrpInfo</code>.
   * @alias module:model/VrrpInfo
   * @class
   */
  var exports = function() {
    var _this = this;













  };

  /**
   * Constructs a <code>VrrpInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VrrpInfo} obj Optional instance to populate.
   * @return {module:model/VrrpInfo} The populated <code>VrrpInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = ApiClient.convertToType(data['state'], 'String');
      }
      if (data.hasOwnProperty('interface')) {
        obj['interface'] = ApiClient.convertToType(data['interface'], 'String');
      }
      if (data.hasOwnProperty('vr_id')) {
        obj['vr_id'] = ApiClient.convertToType(data['vr_id'], 'String');
      }
      if (data.hasOwnProperty('priority')) {
        obj['priority'] = ApiClient.convertToType(data['priority'], 'String');
      }
      if (data.hasOwnProperty('advert_int')) {
        obj['advert_int'] = ApiClient.convertToType(data['advert_int'], 'String');
      }
      if (data.hasOwnProperty('auth_type')) {
        obj['auth_type'] = ApiClient.convertToType(data['auth_type'], 'String');
      }
      if (data.hasOwnProperty('auth_pass')) {
        obj['auth_pass'] = ApiClient.convertToType(data['auth_pass'], 'String');
      }
      if (data.hasOwnProperty('vips')) {
        obj['vips'] = ApiClient.convertToType(data['vips'], ['String']);
      }
      if (data.hasOwnProperty('notify_master')) {
        obj['notify_master'] = ApiClient.convertToType(data['notify_master'], 'String');
      }
      if (data.hasOwnProperty('notify_backup')) {
        obj['notify_backup'] = ApiClient.convertToType(data['notify_backup'], 'String');
      }
      if (data.hasOwnProperty('notify_fault')) {
        obj['notify_fault'] = ApiClient.convertToType(data['notify_fault'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {module:model/VrrpInfo.StateEnum} state
   */
  exports.prototype['state'] = undefined;
  /**
   * @member {String} interface
   */
  exports.prototype['interface'] = undefined;
  /**
   * @member {String} vr_id
   */
  exports.prototype['vr_id'] = undefined;
  /**
   * @member {String} priority
   */
  exports.prototype['priority'] = undefined;
  /**
   * @member {String} advert_int
   */
  exports.prototype['advert_int'] = undefined;
  /**
   * @member {module:model/VrrpInfo.AuthTypeEnum} auth_type
   */
  exports.prototype['auth_type'] = undefined;
  /**
   * @member {String} auth_pass
   */
  exports.prototype['auth_pass'] = undefined;
  /**
   * @member {Array.<String>} vips
   */
  exports.prototype['vips'] = undefined;
  /**
   * @member {String} notify_master
   */
  exports.prototype['notify_master'] = undefined;
  /**
   * @member {String} notify_backup
   */
  exports.prototype['notify_backup'] = undefined;
  /**
   * @member {String} notify_fault
   */
  exports.prototype['notify_fault'] = undefined;


  /**
   * Allowed values for the <code>state</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StateEnum = {
    /**
     * value: "Master"
     * @const
     */
    "Master": "Master",
    /**
     * value: "Backup"
     * @const
     */
    "Backup": "Backup"  };

  /**
   * Allowed values for the <code>auth_type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.AuthTypeEnum = {
    /**
     * value: "PASS"
     * @const
     */
    "PASS": "PASS",
    /**
     * value: "AH"
     * @const
     */
    "AH": "AH"  };


  return exports;
}));


