/**
 * PRISM NBAPI
 * This is a PRISM NBAPI API Client module.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PrismNbapi);
  }
}(this, function(expect, PrismNbapi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PrismNbapi.InterfaceInfoDetail();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InterfaceInfoDetail', function() {
    it('should create an instance of InterfaceInfoDetail', function() {
      // uncomment below and update the code to test InterfaceInfoDetail
      //var instane = new PrismNbapi.InterfaceInfoDetail();
      //expect(instance).to.be.a(PrismNbapi.InterfaceInfoDetail);
    });

    it('should have the property port (base name: "port")', function() {
      // uncomment below and update the code to test the property port
      //var instane = new PrismNbapi.InterfaceInfoDetail();
      //expect(instance).to.be();
    });

    it('should have the property ipAddress (base name: "ip_address")', function() {
      // uncomment below and update the code to test the property ipAddress
      //var instane = new PrismNbapi.InterfaceInfoDetail();
      //expect(instance).to.be();
    });

    it('should have the property intfName (base name: "intf_name")', function() {
      // uncomment below and update the code to test the property intfName
      //var instane = new PrismNbapi.InterfaceInfoDetail();
      //expect(instance).to.be();
    });

    it('should have the property tenantName (base name: "tenant_name")', function() {
      // uncomment below and update the code to test the property tenantName
      //var instane = new PrismNbapi.InterfaceInfoDetail();
      //expect(instance).to.be();
    });

    it('should have the property hwAddress (base name: "hw_address")', function() {
      // uncomment below and update the code to test the property hwAddress
      //var instane = new PrismNbapi.InterfaceInfoDetail();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new PrismNbapi.InterfaceInfoDetail();
      //expect(instance).to.be();
    });

    it('should have the property vlanId (base name: "vlan_id")', function() {
      // uncomment below and update the code to test the property vlanId
      //var instane = new PrismNbapi.InterfaceInfoDetail();
      //expect(instance).to.be();
    });

    it('should have the property translate (base name: "translate")', function() {
      // uncomment below and update the code to test the property translate
      //var instane = new PrismNbapi.InterfaceInfoDetail();
      //expect(instance).to.be();
    });

    it('should have the property stp (base name: "stp")', function() {
      // uncomment below and update the code to test the property stp
      //var instane = new PrismNbapi.InterfaceInfoDetail();
      //expect(instance).to.be();
    });

    it('should have the property stats (base name: "stats")', function() {
      // uncomment below and update the code to test the property stats
      //var instane = new PrismNbapi.InterfaceInfoDetail();
      //expect(instance).to.be();
    });

  });

}));
