/**
 * PRISM NBAPI
 * This is a PRISM NBAPI API Client module.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PrismNbapi);
  }
}(this, function(expect, PrismNbapi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PrismNbapi.MulticastInfo();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MulticastInfo', function() {
    it('should create an instance of MulticastInfo', function() {
      // uncomment below and update the code to test MulticastInfo
      //var instane = new PrismNbapi.MulticastInfo();
      //expect(instance).to.be.a(PrismNbapi.MulticastInfo);
    });

    it('should have the property dfRouteDist (base name: "df_route_dist")', function() {
      // uncomment below and update the code to test the property dfRouteDist
      //var instane = new PrismNbapi.MulticastInfo();
      //expect(instance).to.be();
    });

    it('should have the property dfRouteMet (base name: "df_route_met")', function() {
      // uncomment below and update the code to test the property dfRouteMet
      //var instane = new PrismNbapi.MulticastInfo();
      //expect(instance).to.be();
    });

    it('should have the property phyint (base name: "phyint")', function() {
      // uncomment below and update the code to test the property phyint
      //var instane = new PrismNbapi.MulticastInfo();
      //expect(instance).to.be();
    });

    it('should have the property rpAddr (base name: "rp_addr")', function() {
      // uncomment below and update the code to test the property rpAddr
      //var instane = new PrismNbapi.MulticastInfo();
      //expect(instance).to.be();
    });

    it('should have the property rpCandi (base name: "rp_candi")', function() {
      // uncomment below and update the code to test the property rpCandi
      //var instane = new PrismNbapi.MulticastInfo();
      //expect(instance).to.be();
    });

    it('should have the property bsrCandi (base name: "bsr_candi")', function() {
      // uncomment below and update the code to test the property bsrCandi
      //var instane = new PrismNbapi.MulticastInfo();
      //expect(instance).to.be();
    });

    it('should have the property sptThreshold (base name: "spt_threshold")', function() {
      // uncomment below and update the code to test the property sptThreshold
      //var instane = new PrismNbapi.MulticastInfo();
      //expect(instance).to.be();
    });

  });

}));
