/**
 * PRISM NBAPI
 * This is a PRISM NBAPI API Client module.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PrismNbapi);
  }
}(this, function(expect, PrismNbapi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PrismNbapi.QosApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('QosApi', function() {
    describe('createQosEntry', function() {
      it('should call createQosEntry successfully', function(done) {
        //uncomment below and update the code to test createQosEntry
        //instance.createQosEntry(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createQosRule', function() {
      it('should call createQosRule successfully', function(done) {
        //uncomment below and update the code to test createQosRule
        //instance.createQosRule(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteQosEntry', function() {
      it('should call deleteQosEntry successfully', function(done) {
        //uncomment below and update the code to test deleteQosEntry
        //instance.deleteQosEntry(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteQosRule', function() {
      it('should call deleteQosRule successfully', function(done) {
        //uncomment below and update the code to test deleteQosRule
        //instance.deleteQosRule(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getQosEntryInfo', function() {
      it('should call getQosEntryInfo successfully', function(done) {
        //uncomment below and update the code to test getQosEntryInfo
        //instance.getQosEntryInfo(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getQosRuleInfo', function() {
      it('should call getQosRuleInfo successfully', function(done) {
        //uncomment below and update the code to test getQosRuleInfo
        //instance.getQosRuleInfo(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
