/**
 * PRISM NBAPI
 * This is a PRISM NBAPI API Client module.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PrismNbapi);
  }
}(this, function(expect, PrismNbapi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PrismNbapi.VrrpApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VrrpApi', function() {
    describe('createVRRP', function() {
      it('should call createVRRP successfully', function(done) {
        //uncomment below and update the code to test createVRRP
        //instance.createVRRP(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createVrrpInTenant', function() {
      it('should call createVrrpInTenant successfully', function(done) {
        //uncomment below and update the code to test createVrrpInTenant
        //instance.createVrrpInTenant(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteVrrpInTenant', function() {
      it('should call deleteVrrpInTenant successfully', function(done) {
        //uncomment below and update the code to test deleteVrrpInTenant
        //instance.deleteVrrpInTenant(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteVrrpo', function() {
      it('should call deleteVrrpo successfully', function(done) {
        //uncomment below and update the code to test deleteVrrpo
        //instance.deleteVrrpo(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllVrrpInfo', function() {
      it('should call getAllVrrpInfo successfully', function(done) {
        //uncomment below and update the code to test getAllVrrpInfo
        //instance.getAllVrrpInfo(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllVrrpInfoInTenant', function() {
      it('should call getAllVrrpInfoInTenant successfully', function(done) {
        //uncomment below and update the code to test getAllVrrpInfoInTenant
        //instance.getAllVrrpInfoInTenant(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOneVrrpInfo', function() {
      it('should call getOneVrrpInfo successfully', function(done) {
        //uncomment below and update the code to test getOneVrrpInfo
        //instance.getOneVrrpInfo(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOneVrrpInfoInTenant', function() {
      it('should call getOneVrrpInfoInTenant successfully', function(done) {
        //uncomment below and update the code to test getOneVrrpInfoInTenant
        //instance.getOneVrrpInfoInTenant(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateVrrpInTenant', function() {
      it('should call updateVrrpInTenant successfully', function(done) {
        //uncomment below and update the code to test updateVrrpInTenant
        //instance.updateVrrpInTenant(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateVrrpo', function() {
      it('should call updateVrrpo successfully', function(done) {
        //uncomment below and update the code to test updateVrrpo
        //instance.updateVrrpo(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
